# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/philipmees/Development/OrderBook/OrderBook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/philipmees/Development/OrderBook/OrderBook

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philipmees/Development/OrderBook/OrderBook/CMakeFiles /Users/philipmees/Development/OrderBook/OrderBook/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/philipmees/Development/OrderBook/OrderBook/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OrderBook

# Build rule for target.
OrderBook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OrderBook
.PHONY : OrderBook

# fast build rule for target.
OrderBook/fast:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/build
.PHONY : OrderBook/fast

Config.o: Config.cpp.o

.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i

.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s

.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/Config.cpp.s
.PHONY : Config.cpp.s

OrdBook.o: OrdBook.cpp.o

.PHONY : OrdBook.o

# target to build an object file
OrdBook.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdBook.cpp.o
.PHONY : OrdBook.cpp.o

OrdBook.i: OrdBook.cpp.i

.PHONY : OrdBook.i

# target to preprocess a source file
OrdBook.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdBook.cpp.i
.PHONY : OrdBook.cpp.i

OrdBook.s: OrdBook.cpp.s

.PHONY : OrdBook.s

# target to generate assembly for a file
OrdBook.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdBook.cpp.s
.PHONY : OrdBook.cpp.s

OrdObject.o: OrdObject.cpp.o

.PHONY : OrdObject.o

# target to build an object file
OrdObject.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdObject.cpp.o
.PHONY : OrdObject.cpp.o

OrdObject.i: OrdObject.cpp.i

.PHONY : OrdObject.i

# target to preprocess a source file
OrdObject.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdObject.cpp.i
.PHONY : OrdObject.cpp.i

OrdObject.s: OrdObject.cpp.s

.PHONY : OrdObject.s

# target to generate assembly for a file
OrdObject.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrdObject.cpp.s
.PHONY : OrdObject.cpp.s

OrderBook.o: OrderBook.cpp.o

.PHONY : OrderBook.o

# target to build an object file
OrderBook.cpp.o:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrderBook.cpp.o
.PHONY : OrderBook.cpp.o

OrderBook.i: OrderBook.cpp.i

.PHONY : OrderBook.i

# target to preprocess a source file
OrderBook.cpp.i:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrderBook.cpp.i
.PHONY : OrderBook.cpp.i

OrderBook.s: OrderBook.cpp.s

.PHONY : OrderBook.s

# target to generate assembly for a file
OrderBook.cpp.s:
	$(MAKE) -f CMakeFiles/OrderBook.dir/build.make CMakeFiles/OrderBook.dir/OrderBook.cpp.s
.PHONY : OrderBook.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OrderBook"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... OrdBook.o"
	@echo "... OrdBook.i"
	@echo "... OrdBook.s"
	@echo "... OrdObject.o"
	@echo "... OrdObject.i"
	@echo "... OrdObject.s"
	@echo "... OrderBook.o"
	@echo "... OrderBook.i"
	@echo "... OrderBook.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

